changelog:
  exclude:
    labels:
      - question
      - wontfix
      - invalid
  categories:
    - title: Exciting New Features 🎉
      labels:
        - enhancement
        - feature
    - title: Squashed Bugs 🐛
      labels:
        - bug
        - breaking-change
    - title: Adminsitrative
      labels:
        - administrative
        - documentation
    - title: Other Changes
      labels:
        - "*"